/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-background": "#1b1b1b",
              "tertiary": "#555e60",
              "secondary-fixed": "#e5e2e1",
              "on-secondary": "#ffffff",
              "surface-dim": "#dadada",
              "on-secondary-fixed-variant": "#474646",
              "error-container": "#ffdad6",
              "on-primary-container": "#4d7400",
              "secondary-fixed-dim": "#c9c6c5",
              "on-surface": "#1b1b1b",
              "secondary": "#5f5e5e",
              "primary-fixed": "#aff833",
              "inverse-surface": "#303030",
              "inverse-on-surface": "#f1f1f1",
              "surface-bright": "#f9f9f9",
              "on-tertiary-fixed": "#121c28",
              "surface-container": "#eeeeee",
              "surface-container-highest": "#e2e2e2",
              "on-error-container": "#93000a",
              "on-surface-variant": "#424935",
              "inverse-primary": "#95da03",
              "error": "#ba1a1a",
              "on-secondary-fixed": "#1c1b1b",
              "on-tertiary-container": "#5f6978",
              "surface-container-low": "#fafafa",
              "surface": "#ffffff",
              "tertiary-fixed": "#d9e3f4",
              "outline-variant": "#c2caaf",
              "tertiary-fixed-dim": "#bdc7d8",
              "on-error": "#ffffff",
              "primary": "#456800",
              "on-secondary-container": "#656464",
              "on-tertiary": "#ffffff",
              "on-tertiary-fixed-variant": "#3e4755",
              "background": "#ffffff",
              "outline": "#727a63",
              "secondary-container": "#ffffff",
              "surface-variant": "#e2e2e2",
              "surface-tint": "#456800",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#121f00",
              "on-primary-fixed-variant": "#334f00",
              "surface-container-lowest": "#ffffff",
              "primary-container": "#b6ff3b",
              "primary-fixed-dim": "#95da03",
              "tertiary-container": "#e0eafb",
              "surface-container-high": "#e8e8e8"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "max-width": "1440px",
              "unit": "4px",
              "margin-desktop": "40px",
              "margin-mobile": "24px",
              "gutter": "24px"
          },
          "fontFamily": {
              "sans": ["Outfit", "sans-serif"],
              "headline-xl": ["Outfit", "sans-serif"],
              "label-xs": ["Outfit", "sans-serif"],
              "body-md": ["Outfit", "sans-serif"],
              "headline-lg-mobile": ["Outfit", "sans-serif"],
              "body-lg": ["Outfit", "sans-serif"],
              "label-sm": ["Outfit", "sans-serif"],
              "headline-lg": ["Outfit", "sans-serif"],
              "display-lg": ["Outfit", "sans-serif"],
              "display-sm": ["Outfit", "sans-serif"],
              "headline-md": ["Outfit", "sans-serif"],
              "headline-sm": ["Outfit", "sans-serif"],
              "body-sm": ["Outfit", "sans-serif"],
              "label-md": ["Outfit", "sans-serif"],
          },
          "fontSize": {
              "headline-xl": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "label-xs": ["10px", { "lineHeight": "1.2", "fontWeight": "500" }],
              "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
          }
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
